name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Please look up the latest version from
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          # Please look up the latest version from
          # https://github.com/semantic-release/semantic-release/releases
          semantic_version: 19.0.2
          branches: |
            [
              'main',
              'master'
            ]
          # https://github.com/semantic-release/changelog
          # https://github.com/semantic-release/git
          # https://www.npmjs.com/package/conventional-changelog-conventionalcommits
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@4.6.3
        env:
          # Needs to be configured as a repository secret.
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_ACTION_PAT }}
